//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventApp.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int IDEqupment { get; set; }
        public int IDCustomer { get; set; }
        public int TypeEvent { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual TypeEvent TypeEvent1 { get; set; }
    }
}
